language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.4" || ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then composer require --dev --no-update phpunit/phpunit ~4.5.0; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs
