#define TK_FAIL                           -1
#define TK_PRAGMA                          1
#define TK_BASE                            2
#define TK_IRIREF                          3
#define TK_DOT                             4
#define TK_PREFIX                          5
#define TK_PNAME_NS                        6
#define TK_SELECT                          7
#define TK_DISTINCT                        8
#define TK_REDUCED                         9
#define TK_STAR                           10
#define TK_LPARENTHESE                    11
#define TK_AS                             12
#define TK_RPARENTHESE                    13
#define TK_CONSTRUCT                      14
#define TK_WHERE                          15
#define TK_LBRACE                         16
#define TK_RBRACE                         17
#define TK_DESCRIBE                       18
#define TK_ASK                            19
#define TK_FROM                           20
#define TK_NAMED                          21
#define TK_GROUP                          22
#define TK_BY                             23
#define TK_HAVING                         24
#define TK_ORDER                          25
#define TK_ASC                            26
#define TK_DESC                           27
#define TK_LIMIT                          28
#define TK_INTEGER                        29
#define TK_OFFSET                         30
#define TK_VALUES                         31
#define TK_SEMICOLON                      32
#define TK_LOAD                           33
#define TK_SILENT                         34
#define TK_INTO                           35
#define TK_CLEAR                          36
#define TK_DROP                           37
#define TK_CREATE                         38
#define TK_ADD                            39
#define TK_TO                             40
#define TK_MOVE                           41
#define TK_COPY                           42
#define TK_INSERTDATA                     43
#define TK_DELETEDATA                     44
#define TK_DELETEWHERE                    45
#define TK_WITH                           46
#define TK_DELETE                         47
#define TK_INSERT                         48
#define TK_USING                          49
#define TK_GRAPH                          50
#define TK_DEFAULT                        51
#define TK_ALL                            52
#define TK_OPTIONAL                       53
#define TK_SERVICE                        54
#define TK_BIND                           55
#define TK_NIL                            56
#define TK_UNDEF                          57
#define TK_SMINUS                         58
#define TK_UNION                          59
#define TK_GroupGraphPattern              60
#define TK_FILTER                         61
#define TK_COMMA                          62
#define TK_A                              63
#define TK_VBAR                           64
#define TK_SLASH                          65
#define TK_HAT                            66
#define TK_PLUS                           67
#define TK_QUESTION                       68
#define TK_EXCLAMATION                    69
#define TK_LBRACKET                       70
#define TK_RBRACKET                       71
#define TK_VAR1                           72
#define TK_VAR2                           73
#define TK_OR                             74
#define TK_AND                            75
#define TK_EQUAL                          76
#define TK_NEQUAL                         77
#define TK_SMALLERTHEN                    78
#define TK_GREATERTHEN                    79
#define TK_SMALLERTHENQ                   80
#define TK_GREATERTHENQ                   81
#define TK_IN                             82
#define TK_NOT                            83
#define TK_MINUS                          84
#define TK_STR                            85
#define TK_LANG                           86
#define TK_LANGMATCHES                    87
#define TK_DATATYPE                       88
#define TK_BOUND                          89
#define TK_URI                            90
#define TK_BNODE                          91
#define TK_RAND                           92
#define TK_ABS                            93
#define TK_CEIL                           94
#define TK_FLOOR                          95
#define TK_ROUND                          96
#define TK_CONCAT                         97
#define TK_STRLEN                         98
#define TK_UCASE                          99
#define TK_LCASE                          100
#define TK_ENCODE_FOR_URI                 101
#define TK_CONTAINS                       102
#define TK_STRSTARTS                      103
#define TK_STRENDS                        104
#define TK_STBEFORE                       105
#define TK_STRAFTER                       106
#define TK_YEAR                           107
#define TK_MONTH                          108
#define TK_DAY                            109
#define TK_HOURS                          110
#define TK_MINUTES                        111
#define TK_SECONDS                        112
#define TK_TIMEZONE                       113
#define TK_TZ                             114
#define TK_NOW                            115
#define TK_UUID                           116
#define TK_STRUUID                        117
#define TK_MD5                            118
#define TK_SHA1                           119
#define TK_SHA256                         120
#define TK_SHA384                         121
#define TK_SHA512                         122
#define TK_COALESCE                       123
#define TK_IF                             124
#define TK_STRLANG                        125
#define TK_STRDT                          126
#define TK_SAMETERM                       127
#define TK_ISIRI                          128
#define TK_ISURI                          129
#define TK_ISBLANK                        130
#define TK_ISLITERAL                      131
#define TK_ISNUMERIC                      132
#define TK_REGEX                          133
#define TK_SUBSTR                         134
#define TK_REPLACE                        135
#define TK_EXISTS                         136
#define TK_COUNT                          137
#define TK_SUM                            138
#define TK_MIN                            139
#define TK_MAX                            140
#define TK_AVG                            141
#define TK_SAMPLE                         142
#define TK_GROUP_CONCAT                   143
#define TK_SEPARATOR                      144
#define TK_LANGTAG                        145
#define TK_DHAT                           146
#define TK_DECIMAL                        147
#define TK_DOUBLE                         148
#define TK_INTEGER_POSITIVE               149
#define TK_DECIMAL_POSITIVE               150
#define TK_DOUBLE_POSITIVE                151
#define TK_INTEGER_NEGATIVE               152
#define TK_DECIMAL_NEGATIVE               153
#define TK_DOUBLE_NEGATIVE                154
#define TK_TRUE                           155
#define TK_FALSE                          156
#define TK_STRING_LITERAL1                157
#define TK_STRING_LITERAL2                158
#define TK_STRING_LITERAL_LONG1           159
#define TK_STRING_LITERAL_LONG2           160
#define TK_PNAME_LN                       161
#define TK_BLANK_NODE_LABEL               162
#define TK_ANON                           163

struct Test {
  const char *z; 
  int test;
  unsigned abc;
};
